# Important Notes:
# fabric.mod.json's modid field cannot be expanded, you must change it manually.
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
version=1.0.0
group=com.jeicrafter
java_version=17

# Common
minecraft_version=1.20.1
mod_name=JEI Crafter
mod_author=Jared
mod_id=jeicrafter
license=LGPL-3.0-only
credits=
description=The description of your mod. \nAccepts multilines.
minecraft_version_range=[1.20.1, 1.22)
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.20.1
parchment_version=2023.09.03

# JEI
jei_version=15.21.0.148
jei_version_range=[15.21.0.148,)
# fabric's version predicate parser does not support [min,) range syntax (falls back to literal equality),
# fabric.mod.json must use comparison operator notation. Forge's mods.toml supports ranges, keep as-is.
jei_version_range_fabric=>=15.21.0.148

# Fabric
fabric_version=0.92.11+1.20.1
fabric_loader_version=0.16.10

taglib_group=com.justenoughtaglib
taglib_version=1.2.0

# Forge
forge_version=47.2.30
forge_loader_version_range=[47,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
